### ISSUE TITLE
Re-style Article navigation

### ISSUE THREAD

**Issue by coren-frankel** [cayleeclaww/AutoimmuneEatsWebsitewTailwind#11]
The Article Section navigation mechanism can look pretty different between articles.

Perhaps by making it into a linked table of contents or vertical list with smaller text-links you could get a more uniform-looking presentation.

Perhaps if you lean into the vertical hierarchy you could fit it on the right column in the desktop display. 

If you end up going vertical, locking the width of a parent element and/or using some sort of text-wrap attribute will be necessary to get a consistent look between varied section string lengths.

Here are a few screenshots that show the issue description:
<img width="1895" alt="Screenshot 2024-02-02 at 3 10 52 PM" src="https://github.com/cayleeclaww/AutoimmuneEatsWebsitewTailwind/assets/104476731/0640a8dc-97ac-4f67-8803-aa184251d4fe">
<img width="493" alt="Screenshot 2024-02-02 at 3 12 29 PM" src="https://github.com/cayleeclaww/AutoimmuneEatsWebsitewTailwind/assets/104476731/281bfe06-7298-4c1c-bfa9-32f66aacb91f">

**Comment by cayleeclaww** [comment]
To maintain consistency with similar large websites (like Healthline), will maintain the more horizontal approach for desktop. However, a vertical option may be the best for mobile views

**Comment by coren-frankel** [comment]
How do you feel about unwrapping the `|` pipes from the anchor tags in the mobile article nav tree? I just noticed it now, but in the small screen example, the Pipes are connected to the preceding text link.
